"""Public CiteGuard package facade."""

from citeguard.contracts import (
    CITATION_VERDICTS,
    CONTRACT_SCHEMA_FILENAME,
    CONTRACT_SCHEMA_VERSION,
    CONTRACT_VERSION,
    EVIDENCE_SCOPES,
    RISK_LEVELS,
    SUPPORT_VERDICTS,
    contract_schema_path,
    load_contract_schema,
)
from citeguard.evidence import EVIDENCE_OBJECT_SCHEMA_VERSION, build_evidence_object
from citeguard.errors import (
    ERROR_CODE_CATEGORY,
    ERROR_CODE_NEXT_ACTION,
    ERROR_CODE_RETRYABLE,
    ERROR_SCHEMA_VERSION,
    error_code_registry,
    error_payload,
)
from citeguard.version import __version__

_VERIFICATION_EXPORTS = {
    "AuditReport",
    "CitationRecord",
    "ClaimSupportAuditItem",
    "ClaimSupportRequest",
    "ClaimSupportSetResult",
    "CounterEvidenceSearchReport",
    "DOCUMENT_AUDIT_SCHEMA_VERSION",
    "DOCUMENT_AUDIT_SNAPSHOT_SCHEMA_VERSION",
    "DocumentAuditError",
    "FieldDiff",
    "NEXT_ACTION_DESCRIPTIONS",
    "REVIEW_ACTION_QUEUE_BY_NEXT_ACTION",
    "REVIEW_ACTION_QUEUE_KEYS",
    "STABLE_NEXT_ACTIONS",
    "SupportAuditReport",
    "SupportAssessment",
    "SupportBackend",
    "SupportResult",
    "SupportVerdict",
    "VerificationResult",
    "Verdict",
    "audit_claim_support",
    "audit_citations",
    "audit_document",
    "available_sources",
    "check_claim_support",
    "check_claim_support_set",
    "enrich_support_payload_with_counterevidence",
    "filter_high_risk_payload",
    "infer_evidence_scope",
    "parse_citation",
    "search_counterevidence_candidates",
    "source_failure_recovery_code",
    "stable_next_action",
    "verification_next_action",
    "verification_recovery_code",
    "verify_citation",
}


def __getattr__(name: str):
    if name in _VERIFICATION_EXPORTS:
        from citeguard import verification

        return getattr(verification, name)
    raise AttributeError(f"module 'citeguard' has no attribute {name!r}")

__all__ = [
    "AuditReport",
    "CITATION_VERDICTS",
    "CitationRecord",
    "ClaimSupportAuditItem",
    "ClaimSupportRequest",
    "ClaimSupportSetResult",
    "CounterEvidenceSearchReport",
    "CONTRACT_SCHEMA_FILENAME",
    "CONTRACT_SCHEMA_VERSION",
    "CONTRACT_VERSION",
    "DOCUMENT_AUDIT_SCHEMA_VERSION",
    "DOCUMENT_AUDIT_SNAPSHOT_SCHEMA_VERSION",
    "DocumentAuditError",
    "EVIDENCE_SCOPES",
    "EVIDENCE_OBJECT_SCHEMA_VERSION",
    "FieldDiff",
    "NEXT_ACTION_DESCRIPTIONS",
    "REVIEW_ACTION_QUEUE_BY_NEXT_ACTION",
    "REVIEW_ACTION_QUEUE_KEYS",
    "RISK_LEVELS",
    "STABLE_NEXT_ACTIONS",
    "SupportAuditReport",
    "SupportAssessment",
    "SupportBackend",
    "SupportResult",
    "SupportVerdict",
    "SUPPORT_VERDICTS",
    "VerificationResult",
    "Verdict",
    "ERROR_SCHEMA_VERSION",
    "ERROR_CODE_NEXT_ACTION",
    "ERROR_CODE_RETRYABLE",
    "ERROR_CODE_CATEGORY",
    "__version__",
    "error_code_registry",
    "error_payload",
    "audit_claim_support",
    "audit_citations",
    "audit_document",
    "available_sources",
    "build_evidence_object",
    "check_claim_support",
    "check_claim_support_set",
    "contract_schema_path",
    "enrich_support_payload_with_counterevidence",
    "filter_high_risk_payload",
    "infer_evidence_scope",
    "load_contract_schema",
    "parse_citation",
    "search_counterevidence_candidates",
    "source_failure_recovery_code",
    "stable_next_action",
    "verification_next_action",
    "verification_recovery_code",
    "verify_citation",
]
