"""Public citation verification API."""

from citeguard.graph import CitationRecord
from citeguard.verifiers import SupportAssessment, SupportBackend
from citeguard.evidence import EVIDENCE_OBJECT_SCHEMA_VERSION, build_evidence_object

from .models import (
    AuditReport,
    FieldDiff,
    NEXT_ACTION_DESCRIPTIONS,
    REVIEW_ACTION_QUEUE_BY_NEXT_ACTION,
    REVIEW_ACTION_QUEUE_KEYS,
    STABLE_NEXT_ACTIONS,
    VerificationResult,
    Verdict,
    available_sources,
    filter_high_risk_payload,
    source_failure_recovery_code,
    stable_next_action,
    verification_next_action,
    verification_recovery_code,
)
from .audit import audit_citations
from .cache import CACHE_SCHEMA_VERSION, CachingMetadataSource, clear_cache, export_cache_records, inspect_cache
from .document_audit import (
    ALLOWED_DOCUMENT_SOURCE_FORMATS,
    ALLOWED_DOCUMENT_SUFFIXES,
    DOCUMENT_AUDIT_SCHEMA_VERSION,
    DOCUMENT_AUDIT_SNAPSHOT_SCHEMA_VERSION,
    DocumentAuditError,
    audit_document,
    configured_document_roots,
)
from .extract import extract_citation_candidates, load_citation_candidates
from .parse import parse_citation
from .resolve import ResolveOutcome, resolve_citation, source_names, verification_match_score
from .support import (
    DEFAULT_SUPPORT_POLICY,
    ClaimSupportAuditItem,
    ClaimSupportRequest,
    ClaimSupportSetResult,
    CounterEvidenceSearchReport,
    SupportDecisionPolicy,
    SupportAuditReport,
    SupportResult,
    SupportVerdict,
    assess_support,
    audit_claim_support,
    check_claim_support,
    check_claim_support_set,
    enrich_support_payload_with_counterevidence,
    infer_evidence_scope,
    infer_evidence_source_name,
    search_counterevidence_candidates,
)
from .support_eval import compute_support_release_summary
from .verify import verify_citation

__all__ = [
    "AuditReport",
    "ALLOWED_DOCUMENT_SOURCE_FORMATS",
    "ALLOWED_DOCUMENT_SUFFIXES",
    "CACHE_SCHEMA_VERSION",
    "CachingMetadataSource",
    "CitationRecord",
    "ClaimSupportRequest",
    "ClaimSupportAuditItem",
    "ClaimSupportSetResult",
    "CounterEvidenceSearchReport",
    "DOCUMENT_AUDIT_SCHEMA_VERSION",
    "DOCUMENT_AUDIT_SNAPSHOT_SCHEMA_VERSION",
    "DEFAULT_SUPPORT_POLICY",
    "DocumentAuditError",
    "EVIDENCE_OBJECT_SCHEMA_VERSION",
    "FieldDiff",
    "NEXT_ACTION_DESCRIPTIONS",
    "REVIEW_ACTION_QUEUE_BY_NEXT_ACTION",
    "REVIEW_ACTION_QUEUE_KEYS",
    "ResolveOutcome",
    "STABLE_NEXT_ACTIONS",
    "SupportDecisionPolicy",
    "SupportAuditReport",
    "SupportAssessment",
    "SupportBackend",
    "SupportResult",
    "SupportVerdict",
    "VerificationResult",
    "Verdict",
    "assess_support",
    "audit_claim_support",
    "audit_citations",
    "audit_document",
    "available_sources",
    "build_evidence_object",
    "filter_high_risk_payload",
    "check_claim_support",
    "check_claim_support_set",
    "compute_support_release_summary",
    "configured_document_roots",
    "enrich_support_payload_with_counterevidence",
    "clear_cache",
    "extract_citation_candidates",
    "export_cache_records",
    "inspect_cache",
    "infer_evidence_scope",
    "infer_evidence_source_name",
    "load_citation_candidates",
    "parse_citation",
    "resolve_citation",
    "search_counterevidence_candidates",
    "source_failure_recovery_code",
    "source_names",
    "stable_next_action",
    "verification_match_score",
    "verification_next_action",
    "verification_recovery_code",
    "verify_citation",
]
